version: "3.8"

services:
  # DOCKER_BUILDKIT=1 docker build --ssh default --target ci-image --tag edbscan-ci .
  ci:
    image: registry.gitlab.com/radix-ai/packages/edbscan/ci:latest
    build:
      context: .
      target: ci-image

  # DOCKER_BUILDKIT=1 docker build --ssh default --target app-image --tag edbscan-app .
  app:
    image: registry.gitlab.com/radix-ai/packages/edbscan:latest
    build:
      context: .
      target: app-image
    command: ["dev"]
    ports:
      - 8000:8000
    volumes:
      - ./src/edbscan/:/app/src/edbscan/
